using System;
using System.Collections.Generic;
using System.Text;

namespace NetworkGenerator;

internal static class NetworkSourceBuilder
{
    public static string Build(IReadOnlyList<NetworkEndpointDefinition> endpoints)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.Append(RuntimePrefix);
        AppendEndpointCatalog(source, endpoints);
        source.Append(RuntimeSuffix);
        return source.ToString();
    }

    private static void AppendEndpointCatalog(StringBuilder source, IReadOnlyList<NetworkEndpointDefinition> endpoints)
    {
        source.AppendLine("    public static class NetworkEndpoints");
        source.AppendLine("    {");

        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        var memberNames = new List<string>();

        foreach (var endpoint in endpoints)
        {
            var memberName = UniqueIdentifier(ToIdentifier(endpoint.Name), usedNames);
            memberNames.Add(memberName);

            if (endpoint.Kind == NetworkEndpointKind.Server)
            {
                source.AppendLine($"        public static readonly TcpServerEndpoint {memberName} = new TcpServerEndpoint(");
                source.AppendLine($"            \"{Escape(endpoint.Name)}\",");
                source.AppendLine($"            \"{Escape(endpoint.Host)}\",");
                source.AppendLine($"            {endpoint.Port},");
                source.AppendLine($"            {endpoint.MaxConnections},");
                source.AppendLine($"            \"{Escape(endpoint.Description)}\");");
            }
            else
            {
                source.AppendLine($"        public static readonly TcpClientEndpoint {memberName} = new TcpClientEndpoint(");
                source.AppendLine($"            \"{Escape(endpoint.Name)}\",");
                source.AppendLine($"            \"{Escape(endpoint.Host)}\",");
                source.AppendLine($"            {endpoint.Port},");
                source.AppendLine($"            \"{Escape(endpoint.Description)}\");");
            }

            source.AppendLine();
        }

        source.AppendLine("        private static readonly INetworkEndpoint[] EndpointList = new INetworkEndpoint[]");
        source.AppendLine("        {");
        foreach (var memberName in memberNames)
        {
            source.AppendLine($"            {memberName},");
        }

        source.AppendLine("        };");
        source.AppendLine();
        source.AppendLine("        public static IReadOnlyList<INetworkEndpoint> All");
        source.AppendLine("        {");
        source.AppendLine("            get { return EndpointList; }");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine();
    }

    private static string Escape(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string UniqueIdentifier(string baseName, HashSet<string> usedNames)
    {
        var candidate = baseName;
        var index = 2;

        while (!usedNames.Add(candidate))
        {
            candidate = baseName + "_" + index;
            index++;
        }

        return candidate;
    }

    private static string ToIdentifier(string value)
    {
        var builder = new StringBuilder();
        foreach (var ch in value)
        {
            builder.Append(char.IsLetterOrDigit(ch) ? ch : '_');
        }

        if (builder.Length == 0)
        {
            builder.Append("Endpoint");
        }

        if (char.IsDigit(builder[0]))
        {
            builder.Insert(0, '_');
        }

        return builder.ToString();
    }

    private const string RuntimePrefix = @"using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.IO;
using System.Net;
using System.Net.Sockets;
using System.Text;
using System.Threading;

namespace Generated.Network
{
    public enum NetworkEndpointKind
    {
        Server,
        Client
    }

";

    private const string RuntimeSuffix = @"    public interface INetworkEndpoint
    {
        string Name { get; }
        string Host { get; }
        int Port { get; }
        string Description { get; }
        NetworkEndpointKind Kind { get; }
        bool IsConnected { get; }
        void Connect();
        void Recv();
        void SendData(byte[] data);
        void SendData(string text);
        void Disconnect();
    }

    public sealed class TcpClientEndpoint : INetworkEndpoint
    {
        private readonly object _sync = new object();
        private SocketConnection _connection;
        private int _recvStarted;

        public TcpClientEndpoint(string name, string host, int port, string description)
        {
            Name = name;
            Host = host;
            Port = port;
            Description = description ?? string.Empty;
        }

        public event Action<byte[]> DataReceived;
        public event Action<Exception> Error;
        public event Action Disconnected;

        public string Name { get; private set; }
        public string Host { get; private set; }
        public int Port { get; private set; }
        public string Description { get; private set; }
        public NetworkEndpointKind Kind { get { return NetworkEndpointKind.Client; } }
        public bool IsConnected { get { return _connection != null && _connection.IsConnected; } }

        public void Connect()
        {
            lock (_sync)
            {
                if (IsConnected)
                {
                    return;
                }

                var client = new TcpClient();
                client.Connect(Host, Port);
                _connection = new SocketConnection(1, client);
                _recvStarted = 0;
            }
        }

        public void Recv()
        {
            if (_connection == null)
            {
                throw new InvalidOperationException(""Call Connect() before Recv()."");
            }

            if (Interlocked.Exchange(ref _recvStarted, 1) == 0)
            {
                ThreadPool.QueueUserWorkItem(ReceiveLoop, _connection);
            }
        }

        public void Recv(Action<byte[]> onData)
        {
            if (onData != null)
            {
                DataReceived += onData;
            }

            Recv();
        }

        public void SendData(byte[] data)
        {
            if (_connection == null)
            {
                throw new InvalidOperationException(""Call Connect() before SendData()."");
            }

            _connection.SendData(data);
        }

        public void SendData(string text)
        {
            SendData(Encoding.UTF8.GetBytes(text ?? string.Empty));
        }

        public void Disconnect()
        {
            lock (_sync)
            {
                if (_connection != null)
                {
                    _connection.Disconnect();
                    _connection = null;
                }

                _recvStarted = 0;
            }
        }

        private void ReceiveLoop(object state)
        {
            var connection = (SocketConnection)state;

            try
            {
                while (connection.IsConnected)
                {
                    var payload = NetworkFrame.Read(connection.Stream);
                    var handler = DataReceived;
                    if (handler != null)
                    {
                        handler(payload);
                    }
                }
            }
            catch (Exception ex)
            {
                var error = Error;
                if (error != null)
                {
                    error(ex);
                }
            }
            finally
            {
                Disconnect();
                var disconnected = Disconnected;
                if (disconnected != null)
                {
                    disconnected();
                }
            }
        }
    }

    public sealed class TcpServerEndpoint : INetworkEndpoint
    {
        private readonly object _sync = new object();
        private readonly ConcurrentDictionary<int, SocketConnection> _connections = new ConcurrentDictionary<int, SocketConnection>();
        private readonly ConcurrentDictionary<int, byte> _receiveLoops = new ConcurrentDictionary<int, byte>();
        private TcpListener _listener;
        private int _nextConnectionId;
        private volatile bool _running;
        private volatile bool _recvEnabled;

        public TcpServerEndpoint(string name, string host, int port, int maxConnections, string description)
        {
            Name = name;
            Host = string.IsNullOrWhiteSpace(host) ? ""0.0.0.0"" : host;
            Port = port;
            MaxConnections = maxConnections < 1 ? 1 : maxConnections;
            Description = description ?? string.Empty;
        }

        public event Action<SocketConnection> ClientConnected;
        public event Action<SocketConnection> ClientDisconnected;
        public event Action<SocketConnection, byte[]> DataReceived;
        public event Action<Exception> Error;

        public string Name { get; private set; }
        public string Host { get; private set; }
        public int Port { get; private set; }
        public int MaxConnections { get; private set; }
        public string Description { get; private set; }
        public NetworkEndpointKind Kind { get { return NetworkEndpointKind.Server; } }
        public bool IsConnected { get { return _running; } }
        public IReadOnlyCollection<SocketConnection> Connections { get { return _connections.Values; } }

        public void Connect()
        {
            lock (_sync)
            {
                if (_running)
                {
                    return;
                }

                var address = Host == ""0.0.0.0"" ? IPAddress.Any : IPAddress.Parse(Host);
                _listener = new TcpListener(address, Port);
                _listener.Start(MaxConnections);
                _running = true;
                ThreadPool.QueueUserWorkItem(AcceptLoop);
            }
        }

        public void Recv()
        {
            _recvEnabled = true;

            foreach (var connection in _connections.Values)
            {
                QueueReceiveLoop(connection);
            }
        }

        public void Recv(Action<SocketConnection, byte[]> onData)
        {
            if (onData != null)
            {
                DataReceived += onData;
            }

            Recv();
        }

        public void SendData(byte[] data)
        {
            foreach (var connection in _connections.Values)
            {
                connection.SendData(data);
            }
        }

        public void SendData(string text)
        {
            SendData(Encoding.UTF8.GetBytes(text ?? string.Empty));
        }

        public void SendData(int connectionId, byte[] data)
        {
            SocketConnection connection;
            if (!_connections.TryGetValue(connectionId, out connection))
            {
                throw new InvalidOperationException(""No connection with id "" + connectionId + "" exists."");
            }

            connection.SendData(data);
        }

        public void SendData(int connectionId, string text)
        {
            SendData(connectionId, Encoding.UTF8.GetBytes(text ?? string.Empty));
        }

        public void Disconnect()
        {
            lock (_sync)
            {
                _running = false;
                _recvEnabled = false;

                if (_listener != null)
                {
                    _listener.Stop();
                    _listener = null;
                }

                foreach (var connection in _connections.Values)
                {
                    connection.Disconnect();
                }

                _connections.Clear();
                _receiveLoops.Clear();
            }
        }

        private void AcceptLoop(object state)
        {
            while (_running)
            {
                try
                {
                    var client = _listener.AcceptTcpClient();
                    var id = Interlocked.Increment(ref _nextConnectionId);
                    var connection = new SocketConnection(id, client);

                    if (!_connections.TryAdd(id, connection))
                    {
                        connection.Disconnect();
                        continue;
                    }

                    var connected = ClientConnected;
                    if (connected != null)
                    {
                        connected(connection);
                    }

                    if (_recvEnabled)
                    {
                        QueueReceiveLoop(connection);
                    }
                }
                catch (SocketException ex)
                {
                    if (_running)
                    {
                        RaiseError(ex);
                    }
                }
                catch (ObjectDisposedException)
                {
                    return;
                }
                catch (Exception ex)
                {
                    if (_running)
                    {
                        RaiseError(ex);
                    }
                }
            }
        }

        private void QueueReceiveLoop(SocketConnection connection)
        {
            if (_receiveLoops.TryAdd(connection.Id, 1))
            {
                ThreadPool.QueueUserWorkItem(ReceiveLoop, connection);
            }
        }

        private void ReceiveLoop(object state)
        {
            var connection = (SocketConnection)state;

            try
            {
                while (_running && connection.IsConnected)
                {
                    var payload = NetworkFrame.Read(connection.Stream);
                    var handler = DataReceived;
                    if (handler != null)
                    {
                        handler(connection, payload);
                    }
                }
            }
            catch (Exception ex)
            {
                if (_running)
                {
                    RaiseError(ex);
                }
            }
            finally
            {
                SocketConnection removed;
                _connections.TryRemove(connection.Id, out removed);
                byte ignored;
                _receiveLoops.TryRemove(connection.Id, out ignored);
                connection.Disconnect();

                var disconnected = ClientDisconnected;
                if (disconnected != null)
                {
                    disconnected(connection);
                }
            }
        }

        private void RaiseError(Exception ex)
        {
            var handler = Error;
            if (handler != null)
            {
                handler(ex);
            }
        }
    }

    public sealed class SocketConnection
    {
        private readonly object _sendLock = new object();
        private readonly TcpClient _client;

        internal SocketConnection(int id, TcpClient client)
        {
            Id = id;
            _client = client;
            Stream = client.GetStream();
            RemoteEndPoint = client.Client.RemoteEndPoint != null
                ? client.Client.RemoteEndPoint.ToString()
                : string.Empty;
        }

        public int Id { get; private set; }
        public string RemoteEndPoint { get; private set; }
        public NetworkStream Stream { get; private set; }
        public bool IsConnected { get { return _client != null && _client.Connected; } }

        public void SendData(byte[] data)
        {
            lock (_sendLock)
            {
                NetworkFrame.Write(Stream, data);
            }
        }

        public void SendData(string text)
        {
            SendData(Encoding.UTF8.GetBytes(text ?? string.Empty));
        }

        public void Disconnect()
        {
            try
            {
                if (Stream != null)
                {
                    Stream.Dispose();
                }
            }
            finally
            {
                _client.Close();
            }
        }
    }

    internal static class NetworkFrame
    {
        private const int MaxPayloadBytes = 10 * 1024 * 1024;

        public static void Write(NetworkStream stream, byte[] payload)
        {
            if (payload == null)
            {
                throw new ArgumentNullException(""payload"");
            }

            if (payload.Length > MaxPayloadBytes)
            {
                throw new InvalidDataException(""Message payload is too large: "" + payload.Length + "" bytes."");
            }

            var lengthPrefix = BitConverter.GetBytes(IPAddress.HostToNetworkOrder(payload.Length));
            stream.Write(lengthPrefix, 0, lengthPrefix.Length);
            stream.Write(payload, 0, payload.Length);
            stream.Flush();
        }

        public static byte[] Read(NetworkStream stream)
        {
            var lengthPrefix = ReadExact(stream, 4);
            var length = IPAddress.NetworkToHostOrder(BitConverter.ToInt32(lengthPrefix, 0));

            if (length < 0 || length > MaxPayloadBytes)
            {
                throw new InvalidDataException(""Invalid message payload length: "" + length + "" bytes."");
            }

            return ReadExact(stream, length);
        }

        private static byte[] ReadExact(NetworkStream stream, int length)
        {
            var buffer = new byte[length];
            var offset = 0;

            while (offset < length)
            {
                var read = stream.Read(buffer, offset, length - offset);
                if (read == 0)
                {
                    throw new EndOfStreamException(""The remote endpoint closed the connection."");
                }

                offset += read;
            }

            return buffer;
        }
    }
}
";
}

