// <auto-generated />
// Source: PacketDefinitions - 복사본.xml
// DataGenerator에서 생성했습니다. 직접 수정하지 마십시오.

using NetworkGenerator.Attributes;
using System.Runtime.InteropServices;

namespace NetworkGenerator.MessageStructs
{
    public enum EMessageID
    {
        e_data_one = 0,
        e_data_one2 = 1
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct CntlCmdUdpData
    {
        [PacketField(1)]
        public byte UvhfCommand { get; set; }

        [PacketField(2)]
        public byte PttStatus { get; set; }

        [PacketField(3)]
        public byte RadioRxVolStatus { get; set; }
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct CntlCmdUdpData2
    {
        [PacketField(1)]
        public byte UvhfCommand { get; set; }

        [PacketField(2)]
        public byte PttStatus { get; set; }

        [PacketField(3)]
        public byte RadioRxVolStatus { get; set; }
    }
}
