using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace CycloneDDSManager.DDS
{
    /// <summary>
    /// Generates portable IDL from the same validated schema used for runtime
    /// Dynamic Type registration.
    /// </summary>
    public static class DdsIdlGenerator
    {
        public static string Generate<T>()
        {
            return Generate(typeof(T));
        }

        public static string Generate(Type topicType)
        {
            if (topicType == null) throw new ArgumentNullException(nameof(topicType));
            return Generate(DdsSchemaCache.Get(topicType));
        }

        public static string Save<T>(string path)
        {
            return Save(typeof(T), path);
        }

        public static string Save(Type topicType, string path)
        {
            if (topicType == null) throw new ArgumentNullException(nameof(topicType));
            if (string.IsNullOrWhiteSpace(path)) throw new ArgumentException("An IDL path is required.", nameof(path));

            string fullPath = Path.GetFullPath(path);
            string directory = Path.GetDirectoryName(fullPath);
            if (!string.IsNullOrEmpty(directory)) Directory.CreateDirectory(directory);
            File.WriteAllText(fullPath, Generate(topicType), new UTF8Encoding(false));
            return fullPath;
        }

        internal static string Generate(DdsObjectSchema root)
        {
            var structures = new List<DdsObjectSchema>();
            var enumerations = new Dictionary<Type, DdsValueSchema>();
            var visited = new HashSet<Type>();
            Collect(root, visited, structures, enumerations);
            ValidateUniqueTypeNames(root, structures, enumerations.Values);

            var builder = new StringBuilder();
            builder.AppendLine("// Generated by CycloneDDSManager from CLR attributes.");
            builder.AppendLine("// Do not edit separately from the annotated C# type.");
            builder.AppendLine();

            string indent = string.Empty;
            if (!string.IsNullOrEmpty(root.Module))
            {
                builder.Append("module ").Append(root.Module).AppendLine();
                builder.AppendLine("{");
                indent = "    ";
            }

            foreach (DdsValueSchema enumeration in enumerations.Values.OrderBy(value => value.IdlTypeName))
            {
                AppendEnum(builder, enumeration, indent);
                builder.AppendLine();
            }

            foreach (DdsObjectSchema structure in structures)
            {
                AppendStructure(builder, structure, indent);
                builder.AppendLine();
            }

            if (!string.IsNullOrEmpty(root.Module))
                builder.AppendLine("};");

            return builder.ToString();
        }

        private static void Collect(
            DdsObjectSchema structure,
            ISet<Type> visited,
            ICollection<DdsObjectSchema> structures,
            IDictionary<Type, DdsValueSchema> enumerations)
        {
            if (!visited.Add(structure.ManagedType)) return;
            foreach (DdsMemberSchema member in structure.Members)
            {
                if (member.ValueType.Kind == DdsValueKind.Enumeration)
                    enumerations[member.ValueType.ManagedType] = member.ValueType;
                else if (member.ValueType.Kind == DdsValueKind.Structure)
                    Collect(member.ValueType.ObjectType, visited, structures, enumerations);
            }
            structures.Add(structure);
        }

        private static void AppendEnum(StringBuilder builder, DdsValueSchema enumeration, string indent)
        {
            builder.Append(indent).Append("enum ").Append(enumeration.IdlTypeName).AppendLine();
            builder.Append(indent).AppendLine("{");
            for (int index = 0; index < enumeration.EnumLiterals.Count; index++)
            {
                DdsEnumLiteralSchema literal = enumeration.EnumLiterals[index];
                builder.Append(indent).Append("    ").Append("@value(")
                    .Append(literal.Value).Append(") ").Append(literal.Name);
                if (index + 1 < enumeration.EnumLiterals.Count) builder.Append(',');
                builder.AppendLine();
            }
            builder.Append(indent).AppendLine("};");
        }

        private static void AppendStructure(StringBuilder builder, DdsObjectSchema structure, string indent)
        {
            if (structure.IsTopicType && !string.IsNullOrWhiteSpace(structure.Description))
            {
                foreach (string line in structure.Description.Replace("\r", string.Empty).Split('\n'))
                    builder.Append(indent).Append("// ").AppendLine(line.Replace("*/", "* /"));
            }

            builder.Append(indent).Append(ExtensibilityAnnotation(structure.Extensibility)).AppendLine();
            builder.Append(indent).Append("struct ").Append(structure.TypeName).AppendLine();
            builder.Append(indent).AppendLine("{");
            foreach (DdsMemberSchema member in structure.Members)
            {
                builder.Append(indent).Append("    ");
                if (member.IsKey) builder.Append("@key ");
                builder.Append(member.ValueType.IdlTypeName).Append(' ')
                    .Append(member.Name).AppendLine(";");
            }
            builder.Append(indent).AppendLine("};");
        }

        private static string ExtensibilityAnnotation(DdsDynamicTypeExtensibility value)
        {
            switch (value)
            {
                case DdsDynamicTypeExtensibility.Appendable: return "@appendable";
                case DdsDynamicTypeExtensibility.Mutable: return "@mutable";
                default: return "@final";
            }
        }

        private static void ValidateUniqueTypeNames(
            DdsObjectSchema root,
            IEnumerable<DdsObjectSchema> structures,
            IEnumerable<DdsValueSchema> enumerations)
        {
            var owners = new Dictionary<string, Type>(StringComparer.Ordinal);
            foreach (DdsObjectSchema structure in structures)
                AddName(owners, structure.TypeName, structure.ManagedType, root);
            foreach (DdsValueSchema enumeration in enumerations)
                AddName(owners, enumeration.IdlTypeName, enumeration.ManagedType, root);
        }

        private static void AddName(
            IDictionary<string, Type> owners,
            string name,
            Type type,
            DdsObjectSchema root)
        {
            Type existing;
            if (owners.TryGetValue(name, out existing) && existing != type)
            {
                throw new DdsSchemaException(root.ManagedType.FullName +
                    " contains multiple CLR types that map to IDL name '" + name + "'.");
            }
            owners[name] = type;
        }
    }
}
