using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace RouteGenerator;

internal static class RouteSourceBuilder
{
    public static string Build(string projectName, IReadOnlyList<RouteDefinition> allRoutes)
    {
        var routes = allRoutes
            .Where(route => string.Equals(route.From, projectName, StringComparison.OrdinalIgnoreCase))
            .ToList();

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("using System.Collections.Generic;");
        source.AppendLine();
        source.AppendLine("namespace Generated.Communication;");
        source.AppendLine();
        source.AppendLine("public enum Protocol");
        source.AppendLine("{");
        source.AppendLine("    Tcp,");
        source.AppendLine("    Udp");
        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine("public sealed record Route(string Target, string Host, Protocol Protocol, int? Port, string Description);");
        source.AppendLine();
        source.AppendLine("public static class CommunicationRoutes");
        source.AppendLine("{");
        source.AppendLine($"    public const string ProjectName = \"{Escape(projectName)}\";");
        source.AppendLine();

        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        var memberNames = new List<string>();
        foreach (var route in routes)
        {
            var memberName = UniqueIdentifier(ToIdentifier(route.To), usedNames);
            memberNames.Add(memberName);
            var protocol = route.Protocol.Equals("TCP", StringComparison.OrdinalIgnoreCase)
                ? "Protocol.Tcp"
                : "Protocol.Udp";
            var port = route.Port.HasValue ? route.Port.Value.ToString() : "null";

            source.AppendLine($"    public static readonly Route {memberName} = new(");
            source.AppendLine($"        Target: \"{Escape(route.To)}\",");
            source.AppendLine($"        Host: \"{Escape(route.Host)}\",");
            source.AppendLine($"        Protocol: {protocol},");
            source.AppendLine($"        Port: {port},");
            source.AppendLine($"        Description: \"{Escape(route.Description)}\");");
            source.AppendLine();
        }

        source.AppendLine("    public static IReadOnlyList<Route> All { get; } = new Route[]");
        source.AppendLine("    {");
        foreach (var memberName in memberNames)
        {
            source.AppendLine($"        {memberName},");
        }

        source.AppendLine("    };");
        source.AppendLine("}");

        return source.ToString();
    }

    private static string Escape(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string UniqueIdentifier(string baseName, HashSet<string> usedNames)
    {
        var candidate = baseName;
        var index = 2;
        while (!usedNames.Add(candidate))
        {
            candidate = $"{baseName}_{index}";
            index++;
        }

        return candidate;
    }

    private static string ToIdentifier(string value)
    {
        var builder = new StringBuilder();
        foreach (var ch in value)
        {
            builder.Append(char.IsLetterOrDigit(ch) ? ch : '_');
        }

        if (builder.Length == 0)
        {
            builder.Append("Route");
        }

        if (char.IsDigit(builder[0]))
        {
            builder.Insert(0, '_');
        }

        return builder.ToString();
    }
}
