using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace RouteGenerator;

internal static class RouteSourceBuilder
{
    public static string Build(string projectName, IReadOnlyList<RouteDefinition> allRoutes)
    {
        var routes = allRoutes
            .Where(route => string.Equals(route.From, projectName, StringComparison.OrdinalIgnoreCase))
            .ToList();

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("using System;");
        source.AppendLine("using System.Collections.Generic;");
        source.AppendLine("using System.IO;");
        source.AppendLine("using System.Net;");
        source.AppendLine("using System.Net.Sockets;");
        source.AppendLine("using System.Text;");
        source.AppendLine();
        source.AppendLine("namespace Generated.Communication");
        source.AppendLine("{");
        AppendRouteModel(source);
        AppendCommunicationRoutes(source, projectName, routes);
        source.AppendLine("}");

        return source.ToString();
    }

    private static void AppendRouteModel(StringBuilder source)
    {
        source.AppendLine("    public enum Protocol");
        source.AppendLine("    {");
        source.AppendLine("        Tcp,");
        source.AppendLine("        Udp");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public sealed class Route : IDisposable");
        source.AppendLine("    {");
        source.AppendLine("        private const int MaxPayloadBytes = 10 * 1024 * 1024;");
        source.AppendLine("        private TcpClient _tcpClient;");
        source.AppendLine("        private NetworkStream _tcpStream;");
        source.AppendLine("        private UdpClient _udpClient;");
        source.AppendLine();
        source.AppendLine("        public Route(string target, string host, Protocol protocol, int? port)");
        source.AppendLine("            : this(target, host, protocol, port, string.Empty)");
        source.AppendLine("        {");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        public Route(string target, string host, Protocol protocol, int? port, string description)");
        source.AppendLine("        {");
        source.AppendLine("            if (string.IsNullOrWhiteSpace(target))");
        source.AppendLine("            {");
        source.AppendLine("                throw new ArgumentException(\"Target is required.\", \"target\");");
        source.AppendLine("            }");
        source.AppendLine();
        source.AppendLine("            if (string.IsNullOrWhiteSpace(host))");
        source.AppendLine("            {");
        source.AppendLine("                throw new ArgumentException(\"Host is required.\", \"host\");");
        source.AppendLine("            }");
        source.AppendLine();
        source.AppendLine("            Target = target;");
        source.AppendLine("            Host = host;");
        source.AppendLine("            Protocol = protocol;");
        source.AppendLine("            Port = port;");
        source.AppendLine("            Description = description ?? string.Empty;");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        public string Target { get; private set; }");
        source.AppendLine("        public string Host { get; private set; }");
        source.AppendLine("        public Protocol Protocol { get; private set; }");
        source.AppendLine("        public int? Port { get; private set; }");
        source.AppendLine("        public string Description { get; private set; }");
        source.AppendLine();
        source.AppendLine("        public string Endpoint");
        source.AppendLine("        {");
        source.AppendLine("            get");
        source.AppendLine("            {");
        source.AppendLine("                return Port.HasValue");
        source.AppendLine("                    ? Protocol + \" \" + Host + \":\" + Port.Value");
        source.AppendLine("                    : Protocol + \" \" + Host;");
        source.AppendLine("            }");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        public bool IsConnected");
        source.AppendLine("        {");
        source.AppendLine("            get");
        source.AppendLine("            {");
        source.AppendLine("                if (Protocol == Protocol.Tcp)");
        source.AppendLine("                {");
        source.AppendLine("                    return _tcpClient != null && _tcpClient.Connected && _tcpStream != null;");
        source.AppendLine("                }");
        source.AppendLine();
        source.AppendLine("                return _udpClient != null;");
        source.AppendLine("            }");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        public void Connect()");
        source.AppendLine("        {");
        source.AppendLine("            EnsurePort();");
        source.AppendLine();
        source.AppendLine("            if (Protocol == Protocol.Tcp)");
        source.AppendLine("            {");
        source.AppendLine("                if (IsConnected)");
        source.AppendLine("                {");
        source.AppendLine("                    return;");
        source.AppendLine("                }");
        source.AppendLine();
        source.AppendLine("                _tcpClient = new TcpClient();");
        source.AppendLine("                _tcpClient.Connect(Host, Port.Value);");
        source.AppendLine("                _tcpStream = _tcpClient.GetStream();");
        source.AppendLine("                return;");
        source.AppendLine("            }");
        source.AppendLine();
        source.AppendLine("            if (_udpClient == null)");
        source.AppendLine("            {");
        source.AppendLine("                _udpClient = new UdpClient();");
        source.AppendLine("                _udpClient.Connect(Host, Port.Value);");
        source.AppendLine("            }");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        public void Send(string message)");
        source.AppendLine("        {");
        source.AppendLine("            if (message == null)");
        source.AppendLine("            {");
        source.AppendLine("                throw new ArgumentNullException(\"message\");");
        source.AppendLine("            }");
        source.AppendLine();
        source.AppendLine("            if (Protocol == Protocol.Tcp)");
        source.AppendLine("            {");
        source.AppendLine("                EnsureTcpConnected();");
        source.AppendLine("                WriteFrame(_tcpStream, message);");
        source.AppendLine("                return;");
        source.AppendLine("            }");
        source.AppendLine();
        source.AppendLine("            if (_udpClient == null)");
        source.AppendLine("            {");
        source.AppendLine("                Connect();");
        source.AppendLine("            }");
        source.AppendLine();
        source.AppendLine("            byte[] payload = Encoding.UTF8.GetBytes(message);");
        source.AppendLine("            _udpClient.Send(payload, payload.Length);");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        public string Recv()");
        source.AppendLine("        {");
        source.AppendLine("            EnsurePort();");
        source.AppendLine();
        source.AppendLine("            if (Protocol == Protocol.Tcp)");
        source.AppendLine("            {");
        source.AppendLine("                EnsureTcpConnected();");
        source.AppendLine("                return ReadFrame(_tcpStream);");
        source.AppendLine("            }");
        source.AppendLine();
        source.AppendLine("            if (_udpClient == null)");
        source.AppendLine("            {");
        source.AppendLine("                _udpClient = new UdpClient(Port.Value);");
        source.AppendLine("            }");
        source.AppendLine();
        source.AppendLine("            IPEndPoint remoteEndPoint = new IPEndPoint(IPAddress.Any, 0);");
        source.AppendLine("            byte[] payload = _udpClient.Receive(ref remoteEndPoint);");
        source.AppendLine("            return Encoding.UTF8.GetString(payload);");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        public void Disconnect()");
        source.AppendLine("        {");
        source.AppendLine("            if (_tcpStream != null)");
        source.AppendLine("            {");
        source.AppendLine("                _tcpStream.Dispose();");
        source.AppendLine("                _tcpStream = null;");
        source.AppendLine("            }");
        source.AppendLine();
        source.AppendLine("            if (_tcpClient != null)");
        source.AppendLine("            {");
        source.AppendLine("                _tcpClient.Close();");
        source.AppendLine("                _tcpClient = null;");
        source.AppendLine("            }");
        source.AppendLine();
        source.AppendLine("            if (_udpClient != null)");
        source.AppendLine("            {");
        source.AppendLine("                _udpClient.Close();");
        source.AppendLine("                _udpClient = null;");
        source.AppendLine("            }");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        public void Dispose()");
        source.AppendLine("        {");
        source.AppendLine("            Disconnect();");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        private void EnsurePort()");
        source.AppendLine("        {");
        source.AppendLine("            if (!Port.HasValue)");
        source.AppendLine("            {");
        source.AppendLine("                throw new InvalidOperationException(\"Route \" + Target + \" requires a port.\");");
        source.AppendLine("            }");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        private void EnsureTcpConnected()");
        source.AppendLine("        {");
        source.AppendLine("            if (_tcpClient == null || _tcpStream == null)");
        source.AppendLine("            {");
        source.AppendLine("                throw new InvalidOperationException(\"Call Connect() before Send() or Recv() for TCP route \" + Target + \".\");");
        source.AppendLine("            }");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        private static void WriteFrame(NetworkStream stream, string message)");
        source.AppendLine("        {");
        source.AppendLine("            byte[] payload = Encoding.UTF8.GetBytes(message);");
        source.AppendLine("            if (payload.Length > MaxPayloadBytes)");
        source.AppendLine("            {");
        source.AppendLine("                throw new InvalidDataException(\"Message payload is too large: \" + payload.Length + \" bytes.\");");
        source.AppendLine("            }");
        source.AppendLine();
        source.AppendLine("            byte[] lengthPrefix = BitConverter.GetBytes(IPAddress.HostToNetworkOrder(payload.Length));");
        source.AppendLine("            stream.Write(lengthPrefix, 0, lengthPrefix.Length);");
        source.AppendLine("            stream.Write(payload, 0, payload.Length);");
        source.AppendLine("            stream.Flush();");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        private static string ReadFrame(NetworkStream stream)");
        source.AppendLine("        {");
        source.AppendLine("            byte[] lengthPrefix = ReadExact(stream, 4);");
        source.AppendLine("            int length = IPAddress.NetworkToHostOrder(BitConverter.ToInt32(lengthPrefix, 0));");
        source.AppendLine("            if (length < 0 || length > MaxPayloadBytes)");
        source.AppendLine("            {");
        source.AppendLine("                throw new InvalidDataException(\"Invalid message payload length: \" + length + \" bytes.\");");
        source.AppendLine("            }");
        source.AppendLine();
        source.AppendLine("            byte[] payload = ReadExact(stream, length);");
        source.AppendLine("            return Encoding.UTF8.GetString(payload);");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        private static byte[] ReadExact(NetworkStream stream, int length)");
        source.AppendLine("        {");
        source.AppendLine("            byte[] buffer = new byte[length];");
        source.AppendLine("            int offset = 0;");
        source.AppendLine();
        source.AppendLine("            while (offset < length)");
        source.AppendLine("            {");
        source.AppendLine("                int read = stream.Read(buffer, offset, length - offset);");
        source.AppendLine("                if (read == 0)");
        source.AppendLine("                {");
        source.AppendLine("                    throw new EndOfStreamException(\"The remote endpoint closed the connection.\");");
        source.AppendLine("                }");
        source.AppendLine();
        source.AppendLine("                offset += read;");
        source.AppendLine("            }");
        source.AppendLine();
        source.AppendLine("            return buffer;");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine();
    }

    private static void AppendCommunicationRoutes(
        StringBuilder source,
        string projectName,
        IReadOnlyList<RouteDefinition> routes)
    {
        source.AppendLine("    public static class CommunicationRoutes");
        source.AppendLine("    {");
        source.AppendLine($"        public const string ProjectName = \"{Escape(projectName)}\";");
        source.AppendLine();

        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        var memberNames = new List<string>();

        foreach (var route in routes)
        {
            var memberName = UniqueIdentifier(ToIdentifier(ToMemberName(route.To)), usedNames);
            memberNames.Add(memberName);

            var protocol = route.Protocol.Equals("TCP", StringComparison.OrdinalIgnoreCase)
                ? "Protocol.Tcp"
                : "Protocol.Udp";
            var port = route.Port.HasValue ? route.Port.Value.ToString() : "null";

            source.AppendLine($"        public static readonly Route {memberName} = new Route(");
            source.AppendLine($"            \"{Escape(route.To)}\",");
            source.AppendLine($"            \"{Escape(route.Host)}\",");
            source.AppendLine($"            {protocol},");
            source.AppendLine($"            {port},");
            source.AppendLine($"            \"{Escape(route.Description)}\");");
            source.AppendLine();
        }

        source.AppendLine("        private static readonly Route[] Routes = new Route[]");
        source.AppendLine("        {");
        foreach (var memberName in memberNames)
        {
            source.AppendLine($"            {memberName},");
        }

        source.AppendLine("        };");
        source.AppendLine();
        source.AppendLine("        public static IReadOnlyList<Route> All");
        source.AppendLine("        {");
        source.AppendLine("            get { return Routes; }");
        source.AppendLine("        }");
        source.AppendLine("    }");
    }

    private static string Escape(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string UniqueIdentifier(string baseName, HashSet<string> usedNames)
    {
        var candidate = baseName;
        var index = 2;
        while (!usedNames.Add(candidate))
        {
            candidate = $"{baseName}_{index}";
            index++;
        }

        return candidate;
    }

    private static string ToIdentifier(string value)
    {
        var builder = new StringBuilder();
        foreach (var ch in value)
        {
            builder.Append(char.IsLetterOrDigit(ch) ? ch : '_');
        }

        if (builder.Length == 0)
        {
            builder.Append("Route");
        }

        if (char.IsDigit(builder[0]))
        {
            builder.Insert(0, '_');
        }

        return builder.ToString();
    }

    private static string ToMemberName(string value)
    {
        const string appSuffix = ".App";
        return value.EndsWith(appSuffix, StringComparison.OrdinalIgnoreCase)
            ? value[..^appSuffix.Length]
            : value;
    }
}
