using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace RouteGenerator;

internal static class RouteSourceBuilder
{
    public static string Build(string projectName, IReadOnlyList<RouteDefinition> allRoutes)
    {
        var outgoingRoutes = allRoutes
            .Where(route => string.Equals(route.From, projectName, StringComparison.OrdinalIgnoreCase))
            .ToList();

        var incomingRoutes = allRoutes
            .Where(route => string.Equals(route.To, projectName, StringComparison.OrdinalIgnoreCase))
            .ToList();

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("using System;");
        source.AppendLine("using System.Buffers.Binary;");
        source.AppendLine("using System.Collections.Concurrent;");
        source.AppendLine("using System.Collections.Generic;");
        source.AppendLine("using System.IO;");
        source.AppendLine("using System.Linq;");
        source.AppendLine("using System.Net;");
        source.AppendLine("using System.Net.Sockets;");
        source.AppendLine("using System.Text;");
        source.AppendLine("using System.Threading;");
        source.AppendLine("using System.Threading.Tasks;");
        source.AppendLine();
        source.AppendLine("namespace Generated.Communication;");
        source.AppendLine();
        AppendRouteModel(source);
        AppendCommunicationRoutes(source, projectName, outgoingRoutes, incomingRoutes);
        AppendNetworkHelpers(source);

        return source.ToString();
    }

    private static void AppendRouteModel(StringBuilder source)
    {
        source.AppendLine("public enum Protocol");
        source.AppendLine("{");
        source.AppendLine("    Tcp,");
        source.AppendLine("    Udp");
        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine("public sealed record Route(");
        source.AppendLine("    string Source,");
        source.AppendLine("    string Target,");
        source.AppendLine("    string Host,");
        source.AppendLine("    Protocol Protocol,");
        source.AppendLine("    int? Port,");
        source.AppendLine("    string Description)");
        source.AppendLine("{");
        source.AppendLine("    public string Endpoint => Port is null");
        source.AppendLine("        ? $\"{Protocol} {Host}\"");
        source.AppendLine("        : $\"{Protocol} {Host}:{Port}\";");
        source.AppendLine("}");
        source.AppendLine();
    }

    private static void AppendCommunicationRoutes(
        StringBuilder source,
        string projectName,
        IReadOnlyList<RouteDefinition> outgoingRoutes,
        IReadOnlyList<RouteDefinition> incomingRoutes)
    {
        source.AppendLine("public static class CommunicationRoutes");
        source.AppendLine("{");
        source.AppendLine($"    public const string ProjectName = \"{Escape(projectName)}\";");
        source.AppendLine();

        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        var outgoingMemberNames = AppendRouteMembers(source, outgoingRoutes, usedNames, route => route.To);
        var incomingMemberNames = AppendRouteMembers(source, incomingRoutes, usedNames, route => $"From_{route.From}");

        AppendRouteList(source, "Outgoing", outgoingMemberNames);
        source.AppendLine();
        AppendRouteList(source, "Incoming", incomingMemberNames);
        source.AppendLine();
        source.AppendLine("    public static IReadOnlyList<Route> All => Outgoing;");
        source.AppendLine("}");
        source.AppendLine();
    }

    private static List<string> AppendRouteMembers(
        StringBuilder source,
        IReadOnlyList<RouteDefinition> routes,
        HashSet<string> usedNames,
        Func<RouteDefinition, string> nameFactory)
    {
        var memberNames = new List<string>();
        foreach (var route in routes)
        {
            var memberName = UniqueIdentifier(ToIdentifier(nameFactory(route)), usedNames);
            memberNames.Add(memberName);

            var protocol = route.Protocol.Equals("TCP", StringComparison.OrdinalIgnoreCase)
                ? "Protocol.Tcp"
                : "Protocol.Udp";
            var port = route.Port.HasValue ? route.Port.Value.ToString() : "null";

            source.AppendLine($"    public static readonly Route {memberName} = new(");
            source.AppendLine($"        Source: \"{Escape(route.From)}\",");
            source.AppendLine($"        Target: \"{Escape(route.To)}\",");
            source.AppendLine($"        Host: \"{Escape(route.Host)}\",");
            source.AppendLine($"        Protocol: {protocol},");
            source.AppendLine($"        Port: {port},");
            source.AppendLine($"        Description: \"{Escape(route.Description)}\");");
            source.AppendLine();
        }

        return memberNames;
    }

    private static void AppendRouteList(StringBuilder source, string propertyName, IReadOnlyList<string> memberNames)
    {
        source.AppendLine($"    public static IReadOnlyList<Route> {propertyName} {{ get; }} = new Route[]");
        source.AppendLine("    {");
        foreach (var memberName in memberNames)
        {
            source.AppendLine($"        {memberName},");
        }

        source.AppendLine("    };");
    }

    private static void AppendNetworkHelpers(StringBuilder source)
    {
        source.AppendLine("public static class CommunicationNetwork");
        source.AppendLine("{");
        source.AppendLine("    private static readonly ConcurrentDictionary<string, CommunicationPeerClient> Clients = new(StringComparer.OrdinalIgnoreCase);");
        source.AppendLine("    private static readonly ConcurrentDictionary<string, CommunicationTcpServer> Servers = new(StringComparer.OrdinalIgnoreCase);");
        source.AppendLine();
        source.AppendLine("    public static async Task ConnectAsync(string target, CancellationToken cancellationToken = default)");
        source.AppendLine("    {");
        source.AppendLine("        var route = FindOutgoingRoute(target, Protocol.Tcp);");
        source.AppendLine("        var client = Clients.GetOrAdd(target, _ => new CommunicationPeerClient(route));");
        source.AppendLine("        await client.ConnectAsync(cancellationToken).ConfigureAwait(false);");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public static void Disconnect(string target)");
        source.AppendLine("    {");
        source.AppendLine("        if (Clients.TryRemove(target, out var client))");
        source.AppendLine("        {");
        source.AppendLine("            client.Dispose();");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public static Task SendAsync(string target, string message, CancellationToken cancellationToken = default)");
        source.AppendLine("        => GetClient(target).SendAsync(message, cancellationToken);");
        source.AppendLine();
        source.AppendLine("    public static Task<string> ReceiveAsync(string target, CancellationToken cancellationToken = default)");
        source.AppendLine("        => GetClient(target).ReceiveAsync(cancellationToken);");
        source.AppendLine();
        source.AppendLine("    public static async Task StartReceiveServerAsync(string source, CancellationToken cancellationToken = default)");
        source.AppendLine("    {");
        source.AppendLine("        var route = FindIncomingRoute(source, Protocol.Tcp);");
        source.AppendLine("        var server = Servers.GetOrAdd(source, _ => new CommunicationTcpServer(route));");
        source.AppendLine("        await server.StartAsync(cancellationToken).ConfigureAwait(false);");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public static Task<string> ReceiveFromAsync(string source, CancellationToken cancellationToken = default)");
        source.AppendLine("        => GetServer(source).ReceiveAsync(cancellationToken);");
        source.AppendLine();
        source.AppendLine("    public static Task ReplyAsync(string source, string message, CancellationToken cancellationToken = default)");
        source.AppendLine("        => GetServer(source).SendAsync(message, cancellationToken);");
        source.AppendLine();
        source.AppendLine("    public static void StopReceiveServer(string source)");
        source.AppendLine("    {");
        source.AppendLine("        if (Servers.TryRemove(source, out var server))");
        source.AppendLine("        {");
        source.AppendLine("            server.Dispose();");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public static async Task SendUdpAsync(string target, string message, CancellationToken cancellationToken = default)");
        source.AppendLine("    {");
        source.AppendLine("        cancellationToken.ThrowIfCancellationRequested();");
        source.AppendLine("        var route = FindOutgoingRoute(target, Protocol.Udp);");
        source.AppendLine("        EnsurePort(route);");
        source.AppendLine("        using var udpClient = new UdpClient();");
        source.AppendLine("        var payload = Encoding.UTF8.GetBytes(message);");
        source.AppendLine("        await udpClient.SendAsync(payload, payload.Length, route.Host, route.Port!.Value).ConfigureAwait(false);");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public static async Task<string> ReceiveUdpFromAsync(string source, CancellationToken cancellationToken = default)");
        source.AppendLine("    {");
        source.AppendLine("        var route = FindIncomingRoute(source, Protocol.Udp);");
        source.AppendLine("        EnsurePort(route);");
        source.AppendLine("        using var udpClient = new UdpClient(route.Port!.Value);");
        source.AppendLine("        var result = await udpClient.ReceiveAsync(cancellationToken).ConfigureAwait(false);");
        source.AppendLine("        return Encoding.UTF8.GetString(result.Buffer);");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private static CommunicationPeerClient GetClient(string target)");
        source.AppendLine("    {");
        source.AppendLine("        if (Clients.TryGetValue(target, out var client))");
        source.AppendLine("        {");
        source.AppendLine("            return client;");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        throw new InvalidOperationException($\"Call ConnectAsync(\\\"{target}\\\") before sending or receiving.\");");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private static CommunicationTcpServer GetServer(string source)");
        source.AppendLine("    {");
        source.AppendLine("        if (Servers.TryGetValue(source, out var server))");
        source.AppendLine("        {");
        source.AppendLine("            return server;");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        throw new InvalidOperationException($\"Call StartReceiveServerAsync(\\\"{source}\\\") before receiving.\");");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private static Route FindOutgoingRoute(string target, Protocol protocol)");
        source.AppendLine("    {");
        source.AppendLine("        var route = CommunicationRoutes.Outgoing.FirstOrDefault(route =>");
        source.AppendLine("            route.Protocol == protocol && string.Equals(route.Target, target, StringComparison.OrdinalIgnoreCase));");
        source.AppendLine("        return route ?? throw new InvalidOperationException($\"No outgoing {protocol} route to '{target}' was generated for {CommunicationRoutes.ProjectName}.\");");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private static Route FindIncomingRoute(string source, Protocol protocol)");
        source.AppendLine("    {");
        source.AppendLine("        var route = CommunicationRoutes.Incoming.FirstOrDefault(route =>");
        source.AppendLine("            route.Protocol == protocol && string.Equals(route.Source, source, StringComparison.OrdinalIgnoreCase));");
        source.AppendLine("        return route ?? throw new InvalidOperationException($\"No incoming {protocol} route from '{source}' was generated for {CommunicationRoutes.ProjectName}.\");");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private static void EnsurePort(Route route)");
        source.AppendLine("    {");
        source.AppendLine("        if (route.Port is null)");
        source.AppendLine("        {");
        source.AppendLine("            throw new InvalidOperationException($\"Route {route.Source} -> {route.Target} requires a port for network I/O.\");");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine("public sealed class CommunicationPeerClient : IDisposable");
        source.AppendLine("{");
        source.AppendLine("    private readonly Route _route;");
        source.AppendLine("    private TcpClient? _client;");
        source.AppendLine("    private NetworkStream? _stream;");
        source.AppendLine();
        source.AppendLine("    public CommunicationPeerClient(Route route)");
        source.AppendLine("    {");
        source.AppendLine("        if (route.Protocol != Protocol.Tcp)");
        source.AppendLine("        {");
        source.AppendLine("            throw new ArgumentException(\"CommunicationPeerClient only supports TCP routes.\", nameof(route));");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        _route = route;");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public bool IsConnected => _client?.Connected == true;");
        source.AppendLine();
        source.AppendLine("    public async Task ConnectAsync(CancellationToken cancellationToken = default)");
        source.AppendLine("    {");
        source.AppendLine("        if (IsConnected)");
        source.AppendLine("        {");
        source.AppendLine("            return;");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        if (_route.Port is null)");
        source.AppendLine("        {");
        source.AppendLine("            throw new InvalidOperationException($\"TCP route {_route.Source} -> {_route.Target} requires a port.\");");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        _client = new TcpClient();");
        source.AppendLine("        await _client.ConnectAsync(_route.Host, _route.Port.Value, cancellationToken).ConfigureAwait(false);");
        source.AppendLine("        _stream = _client.GetStream();");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public async Task SendAsync(string message, CancellationToken cancellationToken = default)");
        source.AppendLine("    {");
        source.AppendLine("        var stream = GetStream();");
        source.AppendLine("        await NetworkMessageFrame.WriteAsync(stream, message, cancellationToken).ConfigureAwait(false);");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public Task<string> ReceiveAsync(CancellationToken cancellationToken = default)");
        source.AppendLine("        => NetworkMessageFrame.ReadAsync(GetStream(), cancellationToken);");
        source.AppendLine();
        source.AppendLine("    public void Disconnect()");
        source.AppendLine("    {");
        source.AppendLine("        _stream?.Dispose();");
        source.AppendLine("        _client?.Dispose();");
        source.AppendLine("        _stream = null;");
        source.AppendLine("        _client = null;");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public void Dispose()");
        source.AppendLine("        => Disconnect();");
        source.AppendLine();
        source.AppendLine("    private NetworkStream GetStream()");
        source.AppendLine("        => _stream ?? throw new InvalidOperationException(\"The TCP client is not connected.\");");
        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine("public sealed class CommunicationTcpServer : IDisposable");
        source.AppendLine("{");
        source.AppendLine("    private readonly Route _route;");
        source.AppendLine("    private TcpListener? _listener;");
        source.AppendLine("    private TcpClient? _client;");
        source.AppendLine("    private NetworkStream? _stream;");
        source.AppendLine();
        source.AppendLine("    public CommunicationTcpServer(Route route)");
        source.AppendLine("    {");
        source.AppendLine("        if (route.Protocol != Protocol.Tcp)");
        source.AppendLine("        {");
        source.AppendLine("            throw new ArgumentException(\"CommunicationTcpServer only supports TCP routes.\", nameof(route));");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        _route = route;");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public async Task StartAsync(CancellationToken cancellationToken = default)");
        source.AppendLine("    {");
        source.AppendLine("        if (_stream is not null)");
        source.AppendLine("        {");
        source.AppendLine("            return;");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        if (_route.Port is null)");
        source.AppendLine("        {");
        source.AppendLine("            throw new InvalidOperationException($\"TCP route {_route.Source} -> {_route.Target} requires a port.\");");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        _listener = new TcpListener(IPAddress.Any, _route.Port.Value);");
        source.AppendLine("        _listener.Start();");
        source.AppendLine("        _client = await _listener.AcceptTcpClientAsync(cancellationToken).ConfigureAwait(false);");
        source.AppendLine("        _stream = _client.GetStream();");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public async Task SendAsync(string message, CancellationToken cancellationToken = default)");
        source.AppendLine("    {");
        source.AppendLine("        var stream = GetStream();");
        source.AppendLine("        await NetworkMessageFrame.WriteAsync(stream, message, cancellationToken).ConfigureAwait(false);");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public Task<string> ReceiveAsync(CancellationToken cancellationToken = default)");
        source.AppendLine("        => NetworkMessageFrame.ReadAsync(GetStream(), cancellationToken);");
        source.AppendLine();
        source.AppendLine("    public void Stop()");
        source.AppendLine("    {");
        source.AppendLine("        _stream?.Dispose();");
        source.AppendLine("        _client?.Dispose();");
        source.AppendLine("        _listener?.Stop();");
        source.AppendLine("        _stream = null;");
        source.AppendLine("        _client = null;");
        source.AppendLine("        _listener = null;");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public void Dispose()");
        source.AppendLine("        => Stop();");
        source.AppendLine();
        source.AppendLine("    private NetworkStream GetStream()");
        source.AppendLine("        => _stream ?? throw new InvalidOperationException(\"The TCP server has not accepted a client yet.\");");
        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine("internal static class NetworkMessageFrame");
        source.AppendLine("{");
        source.AppendLine("    private const int MaxPayloadBytes = 10 * 1024 * 1024;");
        source.AppendLine();
        source.AppendLine("    public static async Task WriteAsync(NetworkStream stream, string message, CancellationToken cancellationToken)");
        source.AppendLine("    {");
        source.AppendLine("        var payload = Encoding.UTF8.GetBytes(message);");
        source.AppendLine("        if (payload.Length > MaxPayloadBytes)");
        source.AppendLine("        {");
        source.AppendLine("            throw new InvalidDataException($\"Message payload is too large: {payload.Length} bytes.\");");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        var lengthPrefix = new byte[4];");
        source.AppendLine("        BinaryPrimitives.WriteInt32BigEndian(lengthPrefix, payload.Length);");
        source.AppendLine("        await stream.WriteAsync(lengthPrefix, cancellationToken).ConfigureAwait(false);");
        source.AppendLine("        await stream.WriteAsync(payload, cancellationToken).ConfigureAwait(false);");
        source.AppendLine("        await stream.FlushAsync(cancellationToken).ConfigureAwait(false);");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    public static async Task<string> ReadAsync(NetworkStream stream, CancellationToken cancellationToken)");
        source.AppendLine("    {");
        source.AppendLine("        var lengthPrefix = await ReadExactAsync(stream, 4, cancellationToken).ConfigureAwait(false);");
        source.AppendLine("        var length = BinaryPrimitives.ReadInt32BigEndian(lengthPrefix);");
        source.AppendLine("        if (length < 0 || length > MaxPayloadBytes)");
        source.AppendLine("        {");
        source.AppendLine("            throw new InvalidDataException($\"Invalid message payload length: {length} bytes.\");");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        var payload = await ReadExactAsync(stream, length, cancellationToken).ConfigureAwait(false);");
        source.AppendLine("        return Encoding.UTF8.GetString(payload);");
        source.AppendLine("    }");
        source.AppendLine();
        source.AppendLine("    private static async Task<byte[]> ReadExactAsync(NetworkStream stream, int length, CancellationToken cancellationToken)");
        source.AppendLine("    {");
        source.AppendLine("        var buffer = new byte[length];");
        source.AppendLine("        var offset = 0;");
        source.AppendLine();
        source.AppendLine("        while (offset < length)");
        source.AppendLine("        {");
        source.AppendLine("            var read = await stream.ReadAsync(buffer.AsMemory(offset, length - offset), cancellationToken).ConfigureAwait(false);");
        source.AppendLine("            if (read == 0)");
        source.AppendLine("            {");
        source.AppendLine("                throw new EndOfStreamException(\"The remote endpoint closed the connection.\");");
        source.AppendLine("            }");
        source.AppendLine();
        source.AppendLine("            offset += read;");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        return buffer;");
        source.AppendLine("    }");
        source.AppendLine("}");
    }

    private static string Escape(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string UniqueIdentifier(string baseName, HashSet<string> usedNames)
    {
        var candidate = baseName;
        var index = 2;
        while (!usedNames.Add(candidate))
        {
            candidate = $"{baseName}_{index}";
            index++;
        }

        return candidate;
    }

    private static string ToIdentifier(string value)
    {
        var builder = new StringBuilder();
        foreach (var ch in value)
        {
            builder.Append(char.IsLetterOrDigit(ch) ? ch : '_');
        }

        if (builder.Length == 0)
        {
            builder.Append("Route");
        }

        if (char.IsDigit(builder[0]))
        {
            builder.Insert(0, '_');
        }

        return builder.ToString();
    }
}
