// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AspNetCoreBlazorEmpty.Models;

public partial class Manufacturer
{
    public int ManufacturerId { get; set; }

    public string ManufacturerName { get; set; }

    public string ManufacturerInc { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}