// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AspNetCoreBlazorEmpty.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public int? ProductPrice { get; set; }

    public int? ProductCategoryId { get; set; }

    public int? ProductManufacturerId { get; set; }

    public virtual Category ProductCategory { get; set; }

    public virtual Manufacturer ProductManufacturer { get; set; }
}