// <auto-generated />
// Source: PacketDefinitions - 복사본.xml
// DataGenerator에서 생성했습니다. 직접 수정하지 마십시오.

using NetworkGenerator.Attributes;
using NetworkGenerator.MessageStructs;
using System.Collections.Generic;

namespace NetworkGenerator.Packets
{
    [DataPakcetObject((int)EMessageID.e_data_one2)]
    public sealed class CntlCmdUdp2
        : DataPacketObject<CntlCmdUdpData2>
    {
        private static readonly Dictionary<string, double>
            ResolutionValues =
                new Dictionary<string, double>
                {
                    { nameof(CntlCmdUdpData2.UvhfCommand), 1.0 },
                    { nameof(CntlCmdUdpData2.PttStatus), 1.0 },
                    { nameof(CntlCmdUdpData2.RadioRxVolStatus), 1.0 }
                };

        private static readonly Dictionary<string, double>
            MaximumValues =
                new Dictionary<string, double>
                {
                    { nameof(CntlCmdUdpData2.UvhfCommand), 2.0 },
                    { nameof(CntlCmdUdpData2.PttStatus), 2.0 },
                    { nameof(CntlCmdUdpData2.RadioRxVolStatus), 99.0 }
                };

        private static readonly Dictionary<string, double>
            MinimumValues =
                new Dictionary<string, double>
                {
                    { nameof(CntlCmdUdpData2.UvhfCommand), 0.0 },
                    { nameof(CntlCmdUdpData2.PttStatus), 0.0 },
                    { nameof(CntlCmdUdpData2.RadioRxVolStatus), 0.0 }
                };

        public override int MessageID
        {
            get { return (int)EMessageID.e_data_one2; }
        }

        public override ushort MessageSync
        {
            get { return 65505; }
        }

        public override CntlCmdUdpData2 m_Data { get; set; }

        protected override Dictionary<string, double> m_Resolutions
        {
            get { return ResolutionValues; }
        }

        protected override Dictionary<string, double> m_MaxValues
        {
            get { return MaximumValues; }
        }

        protected override Dictionary<string, double> m_MinValues
        {
            get { return MinimumValues; }
        }
    }
}
